server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:franchise-secure-password-2024@mongodb.franchise-management.local:27017/franchise_db?authSource=admin}
  webflux:
    cors:
      allowed-origins:
        - "*"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: false
      max-age: 3600

logging:
  level:
    co.com.bancolombia: INFO
    reactor.netty: INFO
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always