server:
  port: 8080

spring:
  application:
    name: "MsFranchiseManagement"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
      auto-index-creation: true
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:4200"
        - "http://localhost:8080"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
      max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.data.repository.core.support: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
